INSERT INTO cities (name) VALUES ('Atlanta'),
                                 ('Chicago'),
                                 ('Dallas'),
                                 ('New York'),
                                 ('Washington');

INSERT INTO streets(name, city_id) VALUES ('Lexington Avenue', 1),
                                          ('Seventh Avenue', 1),
                                          ('Madison Avenue', 2),
                                          ('Fifth Avenue', 2),
                                          ('Liberty Street', 3),
                                          ('Stone Street', 3),
                                          ('Marketfield Street', 4),
                                          ('Whitehall Street', 4),
                                          ('South William Street', 4),
                                          ('Pearl Street', 4),
                                          ('Beaver Street', 5),
                                          ('Broad Street', 5),
                                          ('Wall Street', 5);
INSERT INTO shops (name, city_id, street_id, house, open_time, close_time) VALUES ('Dover Street Market', 1, 1, '144A', '09:00:00', '23:00:00'),
                                                                                  ('Fenwick', 2, 3, '567/2', '15:00:00', '00:00:00'),
                                                                                  ('Fortnum & Mason ', 3, 5, '7', '08:00:00', '18:00:00'),
                                                                                  ('Goodhood', 4, 7, '2', '11:00:00', '16:00:00'),
                                                                                  ('Harrods', 5, 11, '32B', '23:00:00', '05:00:00'),
                                                                                  ('Harvey Nichols', 1, 1, '8', '23:00:00', '08:00:00'),
                                                                                  ('Apple Alley', 2, 4, '777', '09:00:00', '16:00:00'),
                                                                                  ('Balsamic', 3, 6, '12', '15:00:00', '19:00:00'),
                                                                                  ('Cavern Cooks', 4, 8, '78/2', '08:00:00', '13:00:00'),
                                                                                  ('Choose And Track', 5, 12, '14', '06:00:00', '10:00:00'),
                                                                                  ('Coffea', 1, 2, '79B', '08:00:00', '22:00:00'),
                                                                                  ('All Things More', 1, 2, '56', '18:00:00', '23:00:00');